codecov:
  require_ci_to_pass: false

coverage:
  precision: 3
  round: down
  range: "50...90"

  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
